# Generated by Django 5.2 on 2025-05-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
