# Generated by Django 5.2 on 2025-05-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_favorite',
        ),
    ]
