# Generated by Django 5.2 on 2025-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='freeze_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
