# Generated by Django 5.2 on 2025-05-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_freeze_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_freeze_days',
            field=models.IntegerField(default=0),
        ),
    ]
