# Generated by Django 5.2 on 2025-06-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_max_freeze_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='remaining_days_at_freeze',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
