# Generated by Django 5.2 on 2025-05-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workout_date_workout_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkout',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
