# Generated by Django 5.2 on 2025-05-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_userworkout_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
