# Generated by Django 5.2 on 2025-05-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workout_workout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_date',
        ),
        migrations.AddField(
            model_name='userworkout',
            name='workout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
